### ISSUE TITLE
Icon is rendering broken.

### ISSUE THREAD

**Issue by karan101292** [entria/react-native-fontawesome#11]
Hey guys, In my android, Icon is rendering broken. My react-native version is 0.44.0
Take a look at screen shot. - The one before **Learn** - text

![font-bug](https://cloud.githubusercontent.com/assets/6022584/26579797/1246fd5a-4553-11e7-8092-a3f470c6bb8a.jpeg)

**Comment by karan101292** [comment]
My bad. forgot to add font files. closing.

**Comment by karan101292** [comment]
forgot to add font files to android directory

**Comment by dfili8** [comment]
@karan101292 Care to share what you mean by adding the font files? I am receiving the same broken icon in my Android project.

**Comment by sibelius** [comment]
@dfili8 you can follow this https://medium.com/@danielskripnik/how-to-add-and-remove-custom-fonts-in-react-native-b2830084b0e4 to add fontawesome files to your project

care to send a PR to improve README.md?
