### ISSUE TITLE
Compatibility with Expo?

### ISSUE THREAD

**Issue by alvaro1728** [entria/react-native-fontawesome#18]
Can this be used in an Expo project?

Thanks,
Alvaro

**Comment by ghoshabhi** [comment]
@alvaro1728 : Expo already comes with vector icons library. I wouldn't install two packages for icons in the same project.

**Comment by nirpeled** [comment]
This works beautifully with Expo

**Comment by sibelius** [comment]
@nirpeled can u send a PR explaining how to use with expo?

**Comment by nirpeled** [comment]
@sibelius Sorry for the late response - I've been away for a while.

Do you still need an example of how to do this?

**Comment by YoshiYo** [comment]
Hi guys,

I have some troubles to use the package with the font loader from Expo.
@nirpeled Can you provide us an example with Expo please?

Thanks in advance,
Guillaume.
