### ISSUE TITLE
Include Example

### ISSUE THREAD

**Issue by rturk** [entria/react-native-fontawesome#2]
- [ ] IOS example
- [ ] Android Example

**Comment by speller** [comment]
Don't understand how to use it. When I try this:

```
import FontAwesome from 'react-native-fontawesome';
...
	render() {
		return (
			<View style={styles.container}>
				<TouchableHighlight style={ styles.imageContainer }>
					<FontAwesome>
						yahoo
					</FontAwesome>
				</TouchableHighlight>
			</View>
		);
	};
```
I get the error: `Touchable child must either be native or forward setNativeProps to a native component`

What to do?

**Comment by sibelius** [comment]
@speller could u try this branch https://github.com/entria/react-native-fontawesome/pull/3

it will solve your problem

**Comment by speller** [comment]
@sibelius The patch is incomplete. It work only if I change the first file of the file to `import React, { Component } from 'react';` . This solved the error messages, but I still can't see any icons, just a blank page. How to change my example above to see icons? I added the `fontawesome-webfont.ttf` to the assets/fonts dir.

**Comment by sibelius** [comment]
ok, I'll fix it

You also need to include the fonts on ios and android

![image](https://cloud.githubusercontent.com/assets/2005841/22786945/aa18d2e0-eec1-11e6-970d-0dfe13bfb587.png)

the name should be `FontAwesome.ttf`

feel free to send a PR to improve README.md instructions

**Comment by speller** [comment]
@sibelius The font filename was the issue, thanks! 

I'm totally newbie in mobile development and React Native so I just learn everything. 

So I suggest following addition to the README:
- Code examples in two notations for newbies such as me (first code notation as in my code example and second in more classic way (I'm sorry, I don't know how to call them in right way))
- Any another exaples if possible.
- Where to put the font files and under what names.
