### ISSUE TITLE
Update to v5 of Font Awesome?

### ISSUE THREAD

**Issue by alshdotme** [entria/react-native-fontawesome#24]
Any chance you could update this to v5? Thanks.

**Comment by sibelius** [comment]
we gonna accept a PR for this

**Comment by qmorallc** [comment]
Hiyya! 

So I might be interested in taking this on. Essentially, do we just need to go through FontAwesomeIcons.js and update it with the new Octals? This seems like a pretty simple project :)

But I could be toootally wrong!

I can see in the download for FA5, in the web fonts directory are the TTF fonts, though they seem to encourage the use of OTF for whatever reason.

**Comment by ksherman** [comment]
Hiyya!

So I might be interested in taking this on. Essentially, do we just need to go through FontAwesomeIcons.js and update it with the new Octals? This seems like a pretty simple project :)

But I could be toootally wrong!

I can see in the download for FA5, in the web fonts directory are the TTF fonts, though they seem to encourage the use of OTF for whatever reason.

**Comment by nirpeled** [comment]
I'd love to help out

**Comment by rgordon95** [comment]
would love to see this brought up to 5.3.1

**Comment by jgcmarins** [comment]
PRs are welcome

**Comment by samirant15** [comment]
I've made it compatible with Font Awesome 5! I've modified FontAwesomeIcons.js and added all the Icons of FA5, I've attached the js and the font I used, Just download it from here:
[FontAwesome5ReactNative.zip](https://github.com/entria/react-native-fontawesome/files/2409011/FontAwesome5ReactNative.zip)
And you're ready to go! 😀

**Comment by JCMais** [comment]
@samirant15 are you able to open a pull request with this?

**Comment by leandrosimoes** [comment]
I just create a [PR](https://github.com/entria/react-native-fontawesome/pull/39) for this, I hope that it is all right to merge.

**Comment by jgcmarins** [comment]
https://github.com/entria/react-native-fontawesome/pull/39
