### ISSUE TITLE
Release new version for previous commits

### ISSUE THREAD

**Issue by baona95** [entria/react-native-fontawesome#26]
Please release a new version as right now latest is 5.7.0 and Text props are not included.

I have to install a patch using github commit.

**Comment by leandrosimoes** [comment]
A [new version](https://www.npmjs.com/package/react-native-fontawesome) was released, please, check if in the new version this problem was fixed and feel free to reopen this issue if wasn't. 

**PS: REMEBER TO SEE THE NEW DOCUMENTATION BECAUSE THERE ARE SOME BREAKING CHANGES**
