### ISSUE TITLE
Heavy Displaying Problem

### ISSUE THREAD

**Issue by PrinzAndreVonLandmann** [entria/react-native-fontawesome#38]
![fontawesomeall](https://user-images.githubusercontent.com/39174514/45206206-bceee480-b284-11e8-8d55-90dcadc52bfa.PNG)

I am only getting less than the half of all Icons displayed (see attatchment).
Is that normal? Or am I doing something wrong?

Thank you for your help in Advance

**Comment by jgcmarins** [comment]
I guess it is something related to fontawesome.

**Comment by PrinzAndreVonLandmann** [comment]
today i found out it seems to be a problem of fontawesome and fontawesome5

**Comment by jgcmarins** [comment]
great, how did you solved?

**Comment by PrinzAndreVonLandmann** [comment]
I didnt solved it at all and I never said that I solved something. :/

well after further research my assumtion was wrong 
it just was just true for the 20 i picked and checked more intense

but now it seem the ones which aren´t displayed are totally random
