### ISSUE TITLE
 Icons not visible in build android and iphone

### ISSUE THREAD

**Issue by glasje** [entria/react-native-fontawesome#55]
I published my project and when I open it on iphone and android the icons are not visualized. Should I add the icons to the project?
attached image
![image](https://user-images.githubusercontent.com/34929785/51754162-5a16b200-209a-11e9-99b9-d129c960579c.png)

**Comment by leandrosimoes** [comment]
Did you put the font files in the right places?
Did you check if the font files names are correct? Like this:
    fa_regular_400.ttf
    fa_solid_900.ttf
    fa_brands_400.ttf
What is the package version that you are using? The last 6.0.1?
Are you using the IconTypes enum to chose between FAR, FAS or FAB?

**Comment by glasje** [comment]
when I installed the package I got the error that the sources were not. solve it by loading the fonts in the app.js

![image](https://user-images.githubusercontent.com/34929785/51762119-999ac980-20ad-11e9-9ab9-3c8662a74b2f.png)

but the problem was generated when I generate the APK. When installing it happens that with the icons.
In development if you see

**Comment by leandrosimoes** [comment]
Get a look in [this](https://medium.com/@kswanie21/custom-fonts-in-react-native-tutorial-for-ios-android-76ceeaa0eb78) tutorial to put the font files in ios and android and see if you are missing something. I think that the problem is that you're loading the files dynamically.

**Comment by glasje** [comment]
For iphone is solved (attached image of iphone).
When I open for the first time the application on Android does not show the icons but if I close the apps and then I go back to this the icons are loaded.
![iphone](https://user-images.githubusercontent.com/34929785/51767354-d8378080-20bb-11e9-8d57-c8b087662a87.jpeg)

**Comment by leandrosimoes** [comment]
Well, I think that it is because the dynamic load of the font files, as I said before. Did you saw my previously answer? Get a look in that article that I linked in the answer to see if you can add the files manually to compile with the app.

**Comment by glasje** [comment]
I managed to solve the problem by loading the sources in the following way.
![image](https://user-images.githubusercontent.com/34929785/51938279-78a6e100-23eb-11e9-9da2-071af5bf48bc.png)

![image](https://user-images.githubusercontent.com/34929785/51938241-6331b700-23eb-11e9-9f29-276cb329c7fe.png)


Thank you very much for the help
