### ISSUE TITLE
Pro rather than free?

### ISSUE THREAD

**Issue by larchapp** [entria/react-native-fontawesome#58]
How do we setup with the Pro pack, rather than just free?

```
FAR: Platform.OS === 'ios' ? 'FontAwesome5FreeRegular' : 'fa_regular_400',
FAS: Platform.OS === 'ios' ? 'FontAwesome5FreeSolid' : 'fa_solid_900',
FAB: Platform.OS === 'ios' ? 'FontAwesome5BrandsRegular' : 'fa_brands_400'
```

**Comment by timoisalive** [comment]
Same problem, how should I use the Pro version of the fonts?

**Comment by jr-k** [comment]
Same problem...

**Comment by larchapp** [comment]
Only thing I can suggest is to use https://github.com/FortAwesome/react-native-fontawesome

**Comment by jr-k** [comment]
@larchapp indeed, that's a great suggestion ! I am able to use FontAwesomePro as well, perfect.

**Comment by leandrosimoes** [comment]
I open a PR that maybe solve this issue. https://github.com/entria/react-native-fontawesome/pull/61
In this version you can use a `pro` property that allow to use pro icons. I know that it is not a great solution, but was the easy way that I found for now.

**Comment by leandrosimoes** [comment]
A [new version](https://www.npmjs.com/package/react-native-fontawesome) was released, please, check if in the new version this problem was fixed and feel free to reopen this issue if wasn't. 

**PS: REMEBER TO SEE THE NEW DOCUMENTATION BECAUSE THERE ARE SOME BREAKING CHANGES**
