### ISSUE TITLE
Fonts not working, showing box with cross or Chinese characters

### ISSUE THREAD

**Issue by devWaleed** [entria/react-native-fontawesome#59]
Fonts are either showing as a box with cross or some Chinese characters.

I have put my .ttf files in assets/fonts folder and run react-native link command.

**Comment by vkachan** [comment]
I have the same issue unfortunately.

**Comment by bmcn99** [comment]
Same here, I am using a different custom font as well so I don't believe that part of it is done incorrectly. I am using "version": "6.0.1"

**Comment by palashjhabak** [comment]
@devWaleed  were you able to get it working ?

**Comment by vkachan** [comment]
@bmcn99 thanks, I got it working after change hyphens to underscores in the file names

**Comment by leandrosimoes** [comment]
I open a PR with that solves the hyphens problem, allowing to use the original files with hyphens. https://github.com/entria/react-native-fontawesome/pull/61

In this PR has a working sample project to so you can see how to use properly, because there are some breaking changes on it.

**Comment by leandrosimoes** [comment]
A [new version](https://www.npmjs.com/package/react-native-fontawesome) was released, please, check if in the new version this problem was fixed and feel free to reopen this issue if wasn't. 

**PS: REMEBER TO SEE THE NEW DOCUMENTATION BECAUSE THERE ARE SOME BREAKING CHANGES**

**Comment by King2231** [comment]
i am using the 7.0.0 version and i am still getting a box with cross.. i tried with parseiconname too but it shows error saying parseIconName is not a function...
