### ISSUE TITLE
Please update NPM JS Readme

### ISSUE THREAD

**Issue by arnebr** [entria/react-native-fontawesome#6]
Hey @rturk,
can you please update the NPM JS Readme :) 
That would be awesome for beginners to better get started with the awesome libary.

Greetings,
Arne

**Comment by rodrigooler** [comment]
Hey @arnebr see https://github.com/entria/react-native-fontawesome#installation-process

**Comment by arnebr** [comment]
Hey @rodrigooler,
Thanks, but I wrote that doku. 

Its just a task reminder  for Rafael (@rturk ) because nobody else has access to the npm repo.

Greetings

**Comment by rturk** [comment]
Hi @arnebr will try to update as soon as possible

**Comment by rturk** [comment]
Including @entria team as owners of this NPM
https://docs.npmjs.com/cli/owner

**Comment by leandrosimoes** [comment]
A [new version](https://www.npmjs.com/package/react-native-fontawesome) was released, please, check if in the new version this problem was fixed and feel free to reopen this issue if wasn't. 

**PS: REMEBER TO SEE THE NEW DOCUMENTATION BECAUSE THERE ARE SOME BREAKING CHANGES**
