### ISSUE TITLE
Can't resolve symbol `IconTypes`

### ISSUE THREAD

**Issue by manishbisht** [entria/react-native-fontawesome#60]
`IconTypes` is not working in react native. It gives the following error `Can't resolve symbol IconTypes`

<img width="681" alt="Screen Shot 2019-07-16 at 11 22 28 AM" src="https://user-images.githubusercontent.com/14255990/61269458-44b65100-a7bc-11e9-8da2-12b73c515df2.png">

**Comment by leandrosimoes** [comment]
I open a PR that if merged will no need this IconTypes anymore: https://github.com/entria/react-native-fontawesome/pull/61

**Comment by leandrosimoes** [comment]
A [new version](https://www.npmjs.com/package/react-native-fontawesome) was released, please, check if in the new version this problem was fixed and feel free to reopen this issue if it wasn't. 

**PS: REMEBER TO SEE THE NEW DOCUMENTATION BECAUSE THERE ARE SOME BREAKING CHANGES**
