### ISSUE TITLE
New version of NPM Package

### ISSUE THREAD

**Issue by leandrosimoes** [entria/react-native-fontawesome#62]
Would be great if the NPM Package was updated with the last modifications and fixes.

**Comment by leandrosimoes** [comment]
@sibelius any chance to do that?

**Comment by sibelius** [comment]
done react-native-fontawesome@7.0.0

**Comment by leandrosimoes** [comment]
@sibelius awesome man! Thanks a lot!

**Comment by sibelius** [comment]
great, we also need to update the example to use the latest react-native version

**Comment by leandrosimoes** [comment]
@sibelius Awesome, I can do that. Would be better if I opened a new issue about that?

**Comment by sibelius** [comment]
sure
