### ISSUE TITLE
Font does not render if white space is added with key name

### ISSUE THREAD

**Issue by pawangiri** [entria/react-native-fontawesome#9]
Thanks for the addon. I was looking for something like this. 
Just a small 🐛  👇 

`<FontAwesome> key</FontAwesome>` should be `<FontAwesome>key</FontAwesome>`
The bug does not allow to use white space with a name of the key and fails silently if added accidently.
One simple solution would be to add .trim() at [ {Icons[children.trim()]} ](https://github.com/entria/react-native-fontawesome/blob/master/Icon.js#L19)

Cheers

**Comment by rodrigooler** [comment]
Nice observation, I'll improve it!

**Comment by rturk** [comment]
@pawangiri this is a GFB. 
Let's keep it simple, main ideia of this package is to make it insanely fast with minimal memory footprint. `trim()` probably the best solution for this corner case

**Comment by sibelius** [comment]
What about this ?

```jsx
import FontAwesome, { Icons } from 'react-native-fontawesome';

...

<FontAwesome>{Icons.chevronDown}</FontAwesome>
```

This will make sure nobody commits a typo when trying to use an icon
